### PR TITLE
uncomment resources, update image

### LINKED ISSUE #463: Operator example.yaml has incorrect indentation
During the bug bash, we found that the `example.yaml` file had the hardware resource limits at the same level as `pvc`. This should instead be aligned with `dataStore` to avoid causing issues when the lines are uncommented.

### PR DESCRIPTION
**Pull request by taroface**
Fixes #463.

### CODE REVIEW

**Review by chrislovecnm — COMMENTED** [review]
You either use one or the other, not both

**Comment by taroface** [comment]
> You either use one or the other, not both

I don't know what this comment means. This PR only uncomments the `resources` object.

I also moved `cockroachDBVersion` to the left because there was confusion about the alignment of commented-out fields. This field is still commented out in favor of `image`.

**Comment by chrislovecnm** [comment]
`cockroachDBVersion` I missed that it was still commented out :)

**Review by chrislovecnm — APPROVED** [review]
LGTM

**Review by keith-mcclellan — COMMENTED** [review]
LGTM

**Pull request merged**
