### PR TITLE
Bump version to 2.0.1

### PR DESCRIPTION
**Pull request by rail**

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Do we need to run openshift CI on this?

**Comment by rail** [comment]
> Do we need to run openshift CI on this?

This is a good idea. We can force a nightly run via https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_CockroachOperator_Nightlies_GkeNightly?mode=builds

**Comment by keith-mcclellan** [comment]
We missed updating latest so I just did that.  This should be ready to submit once the red hat outage is over

**Review by keith-mcclellan — APPROVED** [review]
LGTM

**Pull request merged**
