### PR TITLE
Working on getting RedHat CSV generating

### PR DESCRIPTION
**Pull request by chrislovecnm**
- moving around files so that operator sdk will pick up the crd and other yaml files by default
- using operator-sdk generate csv --csv-version 1.0.0 to generate the  CSV file

_TODO_

- [x] get rid of warnings
- [x] test bundle
- [x] do we need a metadata directory - we do not
- [ ] cut another version to make sure it is working
- [x] We need a RBAC role, serviceaccount and a binding named the same as cockroach-operator
- [x] YAML Copywrite header removed?
- [ ] is a status field working
- [ ] operator image name replaced in bundle
- [ ] test operator in RH CI

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@keith-mcclellan I have checked the start of a generated CSV for you. The openshit documentation are using a VERY old version of the `operator-sdk` and I hope this will work.  I am getting the warning that we need to fill out the following fields in the CSV, also we need the container published into a public docker registry.

```console
WARN[0000] Could not detect project root. Ensure that this command runs from the project root directory.
INFO[0000] Generating CSV manifest version 1.0.0
WARN[0000] Required csv fields not filled in file cockroach-operator.clusterserviceversion.yaml:
	spec.description
	spec.keywords
	spec.provider
INFO[0000] CSV manifest generated successfully
```

^ We need to fill out the following.

**Comment by keith-mcclellan** [comment]
I added a branch with manually modified config files for your reference - lets discuss when you have a second.

**Comment by keith-mcclellan** [comment]
we also need to support overriding spec.image.name as a variable (RELATED_IMAGE_COCKROACH) passed in to the operator container rather than requiring it be set via the CR.  This is to allow for offline use of the operator in disconnected env.  the openshift team provided these docs: https://redhat-connect.gitbook.io/certified-operator-guide/appendix/offline-enabled-operators#golang-operators

**Comment by chrislovecnm** [comment]
```
WARNING: csv metadata.annotations.description not defined [1.0.0/cockroach-operator.v1.0.0.clusterserviceversion.yaml]
WARNING: csv metadata.annotations.support not defined [1.0.0/cockroach-operator.v1.0.0.clusterserviceversion.yaml]
WARNING: csv metadata.annotations.certified not defined. [1.0.0/cockroach-operator.v1.0.0.clusterserviceversion.yaml]
WARNING: csv metadata.annotations.description not defined.Without this field, the description displayed in the tiles of the UI will be a truncated version of spec.description. [cockroach-operator/cockroach-operator.package.yaml]
WARNING: csv metadata.annotations.repository not defined.Without this field, the link to the operator source code will not be displayed in the UI. [cockroach-operator/cockroach-operator.package.yaml]
WARNING: csv spec.maintainers not defined. Without this field, the operator details page will not display the name and contact for users to get support in using the operator. The field should be a yaml list of name & email pairs. [cockroach-operator/cockroach-operator.package.yaml]
WARNING: CrdbCluster CRD does not have an entry in alm-examples - please add such an example CR. [cockroach-operator/cockroach-operator.package.yaml]
```

I am getting only the following warning now. And I am uncertain about zipping up the package, but we are a lot closer I think

**Comment by keith-mcclellan** [comment]
[
[sept3-operator-scorecard-tests.log](https://github.com/cockroachdb/cockroach-operator/files/5174800/sept3-operator-scorecard-tests.log)
](url) Finally making some progress again but still not passing all the scorecard tests.  @chrislovecnm

**Comment by keith-mcclellan** [comment]
@chrislovecnm here's the current version of my hand-edited config files as well

[metadata.zip](https://github.com/cockroachdb/cockroach-operator/files/5174918/metadata.zip)

**Comment by chrislovecnm** [comment]
Closing

**Pull request closed without merging**
