### PR TITLE
Document CR fields

### PR DESCRIPTION
**Pull request by vladdy**
Add comments for structures used in custom resources. Also cleanup of unused structured.

### CODE REVIEW

**Comment by vladdy** [comment]
@chrisseto, @joshimhoff, could you, folks review this when you have a moment? Looks like I don't have permissions to modify reviewers now.

**Comment by chrislovecnm** [comment]
This is awesome!! I will take a look at this on Monday @vladdy

**Comment by chrislovecnm** [comment]
@chrisseto can you merge?

**Comment by chrislovecnm** [comment]
@vladdy thank-you for taking your own time to do this PR.  This was very very helpful.

**Pull request merged**
