### PR TITLE
Adding logging with e2e

### PR DESCRIPTION
**Pull request by chrislovecnm**
This PR adds pod level logging when an error has occurred during e2e.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Do not merge, I'm trying to test this

**Review by keith-mcclellan — APPROVED** [review]
LGTM, this might help us troubleshoot some of our other issues too

**Comment by chrislovecnm** [comment]
This was not working quite as expected.  Please do not merge

**Review by udnay — APPROVED** [review]
LGTM

**Pull request closed without merging**
