### PR TITLE
Add feature gate: MultipleNamespaces to install CockroachDB into different namespaces (#561)

### PR DESCRIPTION
**Pull request by AaronLinOops**
This PR add a new feature gate named `MultipleNamespaces` to allow cockroach-operator create and control CockroachDB in multiple namespace. 

This PR is trying to fix issue: [Create cluster in a different namespace than the operator ](https://github.com/cockroachdb/cockroach-operator/issues/561)

## How it works
When this feature gate enable, `controller-runtime/manager.Manager` will be created without namespace set. so the operator can watch all the CrdbClusters in different namespace.

## How to use it

Run the command line below to create CockroachDB in a namespace: cockroach-001

``` bash 
$> kubectl apply -f examples/example-multiple-namespaces.yaml
```

Run the command line below to create a Client pod in the same namespace:

``` bash 
$> kubectl create -f examples/client-secure-operator-multiple-namespaces.yaml -n cockroach-001
```

Result: 
``` bash
$> kubectl get pods -A                                                                                                                                                                                           AarondeMBP: Thu Oct 21 13:06:05 2021

NAMESPACE            NAME                                        READY   STATUS    RESTARTS   AGE
cockroach-001        cockroachdb-0                               1/1     Running   0          34m
cockroach-001        cockroachdb-1                               1/1     Running   0          34m
cockroach-001        cockroachdb-2                               1/1     Running   0          34m
cockroach-001        cockroachdb-client-secure                   1/1     Running   0          33m
default              cockroach-operator-69df6dcb74-nsflg         1/1     Running   0          35m
kube-system          coredns-78fcd69978-8sc7w                    1/1     Running   0          35m
kube-system          coredns-78fcd69978-whqvv                    1/1     Running   0          35m
kube-system          etcd-dev-control-plane                      1/1     Running   0          35m
kube-system          kindnet-5tg74                               1/1     Running   0          35m
kube-system          kube-apiserver-dev-control-plane            1/1     Running   0          35m
kube-system          kube-controller-manager-dev-control-plane   1/1     Running   0          35m
kube-system          kube-proxy-lnkrv                            1/1     Running   0          35m
kube-system          kube-scheduler-dev-control-plane            1/1     Running   0          35m
local-p

```

**Checklist**

* [x] I have added these changes to the changelog (or it's not applicable).

### CODE REVIEW

**Comment by keith-mcclellan** [comment]
@AaronLinOops This is really great, but to merge this we'd need an e2e test that installs the database in multiple namespaces and fails if it isn't successful.  Is that something you feel like you can add?

**Comment by AaronLinOops** [comment]
> @AaronLinOops This is really great, but to merge this we'd need an e2e test that installs the database in multiple namespaces and fails if it isn't successful. Is that something you feel like you can add?

@keith-mcclellan sure, Let me fix it early next week.

**Comment by pseudomuto** [comment]
Hey @AaronLinOops I think this has been addressed as of v2.4.0. The operator can now run as either namespace or cluster scoped and has support for limiting the namespaces to a fixed list if that's desired.

**Comment by AaronLinOops** [comment]
> Hey @AaronLinOops I think this has been addressed as of v2.4.0. The operator can now run as either namespace or cluster scoped and has support for limiting the namespaces to a fixed list if that's desired.

Hi @pseudomuto , thanks for informing this. I think I should follow the roadmap, so maybe I should withdraw this PR. :-)

**Comment by pseudomuto** [comment]
Hey @AaronLinOops thanks so much for the PR! As mentioned above this functionality is already available in the operator, so I'm going to close this.

**Comment by pseudomuto** [comment]
Hey @AaronLinOops thanks so much for the PR! As mentioned above this functionality is already available in the operator, so I'm going to close this.

**Pull request closed without merging**
