### PR TITLE
Add "latest" tag

### PR DESCRIPTION
**Pull request by rail**
In some cases the operator image should be also pushed to the `latest`
tag.`

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@rail in what cases? I have lost production pods because of the wonderful “latest” tag.

**Comment by rail** [comment]
> @rail in what cases? I have lost production pods because of the wonderful “latest” tag. So I am not a huge fan of having latest. Do we need this?

I totally agree, "latest" is evil. Right now we publish to dockerhub and there is the "latest" tag. If we are OK removing it, I would retract this PR. :)

**Comment by rail** [comment]
@keith-mcclellan what you say, do we really need the "latest" tag in docker hub?

**Comment by keith-mcclellan** [comment]
We either need to keep the 'latest' tag up to date or remove it entirely. I don't think DockerHub allows you to remove it.  I think the Red Hat registry also requires the latest tag.  If we can remove them entirely I'm all for it.

**Comment by keith-mcclellan** [comment]
Screen Shot 2021-04-22 at 10 40 57 AM
The Red Hat Registry auto-populates latest.

**Comment by keith-mcclellan** [comment]
fwiw our configuration files should NEVER reference the latest tag to avoid the scenario that @chrislovecnm is describing because I agree it's not something we want to encourage people to use.

**Comment by rail** [comment]
I'll remove the latest tag from dockerhub.

**Pull request closed without merging**
