### PR TITLE
Set maturity to stable

### PR DESCRIPTION
**Pull request by rail**

### CODE REVIEW

**Review by keith-mcclellan — APPROVED** [review]
LGTM

**Comment by udnay** [comment]
LGTM, do we flip this back to beta once we start doing more feature work or are we doing a 2.0.0 release branch?

**Comment by rail** [comment]
> LGTM, do we flip this back to beta once we start doing more feature work or are we doing a 2.0.0 release branch?

Not sure... Maybe we should make this overridable?

**Comment by udnay** [comment]
I think it's fine for today so that we don't add in too much complexity. I'd like to err on the side of simplicity for trying to publish this to openshift today. If we do need to make it overridable then lets create a ticket for it.

**Pull request merged**
