### PR TITLE
add maxlength on jobName using slug

### PR DESCRIPTION
**Pull request by alinadonisa**

### CODE REVIEW

**Review by keith-mcclellan — APPROVED** [review]
LGTM

**Comment by chrislovecnm** [comment]
@rail how do I get CI to run again. I ran the e2e again which passed, but this is still blocked.

**Comment by alinadonisa** [comment]
> Apparently you need to rerun both "End-To-End" and "Github CI", so the latter greens up.
> 
> BTW, it looks like the following test is flaky:
> 
> ```
>     TestUpgradesMinorVersion/upgrades_the_cluster_to_the_next_patch_version: assert.go:123: 
>         	Error Trace:	assert.go:123
>         	            				e2e_test.go:172
>         	Error:      	Received unexpected error:
>         	            	timed out waiting for the condition
>         	Test:       	TestUpgradesMinorVersion/upgrades_the_cluster_to_the_next_patch_version
> --- FAIL: TestUpgradesMinorVersion (490.76s)
>     --- PASS: TestUpgradesMinorVersion/creates_a_1-node_secure_cluster (80.01s)
>     --- FAIL: TestUpgradesMinorVersion/upgrades_the_cluster_to_the_next_patch_version (410.18s)
> ```
> 
> I wonder if we should fix this in a separate PR.

@rail  Yes... I am fixing the tests  on another PR

**Comment by rail** [comment]
> @rail Yes... I am fixing the tests on another PR

Thank you!

BTW, re-running "GitHub CI" only should automatically trigger the failed deps and green up the status.

**Pull request merged**
